export const FETCH_MENUS_PENDING = 'FETCH_MENUS_PENDING';
export const FETCH_MENUS_SUCCESS = 'FETCH_MENUS_SUCCESS';
export const FETCH_MENUS_ERROR = 'FETCH_MENUS_SUCCESS';
export const SET_ACTIVE_MENU_ID = "SET_ACTIVE_USER_ID";
export const EDIT_TITLE = 'EDIT_TITLE';
export const  SUBMIT_TITLE = 'SUBMIT_TITLE';
export const EDIT_TEXT = 'EDIT_TEXT';
export const SUBMIT_TEXT = 'SUBMIT_TEXT';
